#!/usr/bin/env bash

# Important: turning on/off Hicache and offload in single engine mode. 0 means disabled, 1 means enabled.
export SGLANG_SERVER_HICACHE_ENABLE=0

# Important: turning on/off Hicache and offload in PD mode. 0 means disabled, 1 means enabled.
export SGLANG_PD_PREFILL_HICACHE_ENABLE=1 
export SGLANG_PD_DECODE_OFFLOAD_ENABLE=0

# Paths
export SGLANG_REPO_ROOT="/workspace/sglang"
export SGLANG_MS_DEV_DIR="${SGLANG_REPO_ROOT}/ms_dev"
export SGLANG_RUNTIME_DIR="${SGLANG_MS_DEV_DIR}/runtime"

# Python / venv
export PYTHON_BIN="/venv/main/bin/python3"
export PIP_BIN="/venv/main/bin/pip"

# Hugging Face cache
export HF_HOME="/workspace/.hf_home"
export HF_HUB_CACHE="${HF_HOME}/hub"

# Runtime dirs (legacy single-server)
export SGLANG_REQUEST_LOG_DIR="${SGLANG_RUNTIME_DIR}/request_logs"
export SGLANG_REQUEST_METRICS_DIR="${SGLANG_RUNTIME_DIR}/request_metrics"
export SGLANG_CRASH_DUMP_DIR="${SGLANG_RUNTIME_DIR}/crash_dump"

# Runtime dirs (PD role-specific)
export SGLANG_ROUTER_LOG_DIR="${SGLANG_RUNTIME_DIR}/router/logs"

export SGLANG_PD_PREFILL_RUNTIME_DIR="${SGLANG_RUNTIME_DIR}/prefill"
export SGLANG_PD_DECODE_RUNTIME_DIR="${SGLANG_RUNTIME_DIR}/decode"

export SGLANG_PD_PREFILL_REQUEST_LOG_DIR="${SGLANG_PD_PREFILL_RUNTIME_DIR}/request_logs"
export SGLANG_PD_PREFILL_REQUEST_METRICS_DIR="${SGLANG_PD_PREFILL_RUNTIME_DIR}/request_metrics"
export SGLANG_PD_PREFILL_CRASH_DUMP_DIR="${SGLANG_PD_PREFILL_RUNTIME_DIR}/crash_dump"

export SGLANG_PD_DECODE_REQUEST_LOG_DIR="${SGLANG_PD_DECODE_RUNTIME_DIR}/request_logs"
export SGLANG_PD_DECODE_REQUEST_METRICS_DIR="${SGLANG_PD_DECODE_RUNTIME_DIR}/request_metrics"
export SGLANG_PD_DECODE_CRASH_DUMP_DIR="${SGLANG_PD_DECODE_RUNTIME_DIR}/crash_dump"

# Model / server config
export SGLANG_MODEL_PATH="meta-llama/Meta-Llama-3.1-8B-Instruct"
#export SGLANG_MODEL_PATH="meta-llama/Meta-Llama-3-8B-Instruct"
export SGLANG_HOST="0.0.0.0"
export SGLANG_ATTENTION_BACKEND="triton"
export SGLANG_SAMPLING_BACKEND="pytorch"
export SGLANG_MEM_FRACTION_STATIC="0.85"

# Optional: single-server HiCache tuning (non-disaggregated mode)
# Set SGLANG_SERVER_HICACHE_ENABLE=1 to enable hierarchical cache on single server.
export SGLANG_SERVER_HICACHE_ENABLE="${SGLANG_SERVER_HICACHE_ENABLE:-0}"
export SGLANG_SERVER_HICACHE_STORAGE_BACKEND="${SGLANG_SERVER_HICACHE_STORAGE_BACKEND:-}"
export SGLANG_SERVER_HICACHE_PREFETCH_POLICY="${SGLANG_SERVER_HICACHE_PREFETCH_POLICY:-timeout}"
export SGLANG_SERVER_HICACHE_WRITE_POLICY="${SGLANG_SERVER_HICACHE_WRITE_POLICY:-write_back}"
export SGLANG_SERVER_HICACHE_IO_BACKEND="${SGLANG_SERVER_HICACHE_IO_BACKEND:-kernel}"
export SGLANG_SERVER_HICACHE_MEM_LAYOUT="${SGLANG_SERVER_HICACHE_MEM_LAYOUT:-page_first}"
export SGLANG_SERVER_HICACHE_RATIO="${SGLANG_SERVER_HICACHE_RATIO:-2}"
export SGLANG_SERVER_HICACHE_SIZE="${SGLANG_SERVER_HICACHE_SIZE:-256}" # in GB; set 0 to use auto sizing
export SGLANG_SERVER_ENABLE_CACHE_REPORT="${SGLANG_SERVER_ENABLE_CACHE_REPORT:-1}"


# Optional logging / tracing
export SGLANG_LOG_REQUESTS_LEVEL="1"
export SGLANG_LOG_REQUESTS_FORMAT="json"
export SGLANG_OTLP_TRACES_ENDPOINT="localhost:4317"
export SGLANG_OTLP_EXPORTER_SCHEDULE_DELAY_MILLIS="500"
export SGLANG_OTLP_EXPORTER_MAX_EXPORT_BATCH_SIZE="64"
export SGLANG_ROUTER_PROMETHEUS_PORT="${SGLANG_ROUTER_PROMETHEUS_PORT:-29000}"

# PD disaggregation for 1 node / 2 GPUs
export SGLANG_PD_ROUTER_PORT="30000"
export SGLANG_PD_DECODE_PORT="30001"
export SGLANG_PD_PREFILL_PORT="30002"

export SGLANG_PD_PREFILL_BASE_GPU_ID="0"
export SGLANG_PD_DECODE_BASE_GPU_ID="1"

# Router/backend host
# host network 전제면 127.0.0.1 유지해도 충분
export SGLANG_PD_BACKEND_HOST="127.0.0.1"
export SGLANG_PD_ROUTER_HOST="0.0.0.0"

# Optional PD settings
export SGLANG_PD_IB_DEVICE="${SGLANG_PD_IB_DEVICE:-}"
export SGLANG_PD_PREFILL_EXTRA_ARGS="${SGLANG_PD_PREFILL_EXTRA_ARGS:-}"
export SGLANG_PD_DECODE_EXTRA_ARGS="${SGLANG_PD_DECODE_EXTRA_ARGS:-}"
export SGLANG_PD_ROUTER_EXTRA_ARGS="${SGLANG_PD_ROUTER_EXTRA_ARGS:-}"


## Optional: prefill HiCache tuning
# Prefill can safely enable hierarchical cache in PD mode.
# Set SGLANG_PD_PREFILL_HICACHE_ENABLE=0 to disable quickly.
export SGLANG_PD_PREFILL_HICACHE_ENABLE="${SGLANG_PD_PREFILL_HICACHE_ENABLE:-1}"
export SGLANG_PD_PREFILL_HICACHE_STORAGE_BACKEND="${SGLANG_PD_PREFILL_HICACHE_STORAGE_BACKEND:-file}"
export SGLANG_PD_PREFILL_HICACHE_PREFETCH_POLICY="${SGLANG_PD_PREFILL_HICACHE_PREFETCH_POLICY:-timeout}"
# export SGLANG_PD_PREFILL_HICACHE_WRITE_POLICY="${SGLANG_PD_PREFILL_HICACHE_WRITE_POLICY:-write_through}"
export SGLANG_PD_PREFILL_HICACHE_WRITE_POLICY="${SGLANG_PD_PREFILL_HICACHE_WRITE_POLICY:-write_back}"
export SGLANG_PD_PREFILL_HICACHE_IO_BACKEND="${SGLANG_PD_PREFILL_HICACHE_IO_BACKEND:-kernel}"
export SGLANG_PD_PREFILL_HICACHE_MEM_LAYOUT="${SGLANG_PD_PREFILL_HICACHE_MEM_LAYOUT:-page_first}"
export SGLANG_PD_PREFILL_HICACHE_RATIO="${SGLANG_PD_PREFILL_HICACHE_RATIO:-2}"
export SGLANG_PD_PREFILL_HICACHE_SIZE="${SGLANG_PD_PREFILL_HICACHE_SIZE:-256}" # in GB; set 0 to use auto sizing
export SGLANG_PD_PREFILL_ENABLE_CACHE_REPORT="${SGLANG_PD_PREFILL_ENABLE_CACHE_REPORT:-1}"

## Optional: decode HiCache tuning (default: decode L2 disabled due current PD decode/radix conflict)
# Decode L2 HiCache currently conflicts with PD decode in this SGLang version.
# Decode uses disaggregation offload path by default (GPU KV -> host/storage).
# L2 hierarchical cache flag remains disabled for decode due radix-cache incompatibility.
# Override examples:
#   export SGLANG_PD_DECODE_OFFLOAD_ENABLE=0                   # disable decode offload
#   export SGLANG_PD_DECODE_HICACHE_STORAGE_BACKEND=mooncake   # or file/hf3fs
#   export MOONCAKE_MASTER=127.0.0.1:50051                     # when backend=mooncake
export SGLANG_PD_DECODE_OFFLOAD_ENABLE="${SGLANG_PD_DECODE_OFFLOAD_ENABLE:-1}"
export SGLANG_PD_DECODE_HICACHE_ENABLE="${SGLANG_PD_DECODE_HICACHE_ENABLE:-0}"
export SGLANG_PD_DECODE_HICACHE_STORAGE_BACKEND="${SGLANG_PD_DECODE_HICACHE_STORAGE_BACKEND:-file}"
export SGLANG_PD_DECODE_HICACHE_PREFETCH_POLICY="${SGLANG_PD_DECODE_HICACHE_PREFETCH_POLICY:-timeout}"
# export SGLANG_PD_DECODE_HICACHE_WRITE_POLICY="${SGLANG_PD_DECODE_HICACHE_WRITE_POLICY:-write_through}"
export SGLANG_PD_DECODE_HICACHE_WRITE_POLICY="${SGLANG_PD_DECODE_HICACHE_WRITE_POLICY:-write_back}"
export SGLANG_PD_DECODE_HICACHE_IO_BACKEND="${SGLANG_PD_DECODE_HICACHE_IO_BACKEND:-kernel}"
export SGLANG_PD_DECODE_HICACHE_MEM_LAYOUT="${SGLANG_PD_DECODE_HICACHE_MEM_LAYOUT:-page_first}"
export SGLANG_PD_DECODE_HICACHE_RATIO="${SGLANG_PD_DECODE_HICACHE_RATIO:-2}"
export SGLANG_PD_DECODE_HICACHE_SIZE="${SGLANG_PD_DECODE_HICACHE_SIZE:-256}" # in GB; set 0 to use auto sizing (based on free host RAM and ratio)
export SGLANG_PD_DECODE_ENABLE_CACHE_REPORT="${SGLANG_PD_DECODE_ENABLE_CACHE_REPORT:-1}"

# Optional: disaggregation timeout settings (in seconds)
export SGLANG_DISAGGREGATION_BOOTSTRAP_TIMEOUT="${SGLANG_DISAGGREGATION_BOOTSTRAP_TIMEOUT:-900}"
export SGLANG_DISAGGREGATION_WAITING_TIMEOUT="${SGLANG_DISAGGREGATION_WAITING_TIMEOUT:-900}"

# Optional PD router timeouts (in seconds)
export SGLANG_PD_ROUTER_REQUEST_TIMEOUT_SECS="${SGLANG_PD_ROUTER_REQUEST_TIMEOUT_SECS:-900}"

# HF token
export HF_TOKEN="${HF_TOKEN:-hf_xxx}"
export HUGGINGFACE_HUB_TOKEN="${HUGGINGFACE_HUB_TOKEN:-$HF_TOKEN}"

mkdir -p "${SGLANG_RUNTIME_DIR}"
mkdir -p "${HF_HOME}"
mkdir -p "${HF_HUB_CACHE}"

mkdir -p "${SGLANG_REQUEST_LOG_DIR}"
mkdir -p "${SGLANG_REQUEST_METRICS_DIR}"
mkdir -p "${SGLANG_CRASH_DUMP_DIR}"

mkdir -p "${SGLANG_ROUTER_LOG_DIR}"

mkdir -p "${SGLANG_PD_PREFILL_REQUEST_LOG_DIR}"
mkdir -p "${SGLANG_PD_PREFILL_REQUEST_METRICS_DIR}"
mkdir -p "${SGLANG_PD_PREFILL_CRASH_DUMP_DIR}"

mkdir -p "${SGLANG_PD_DECODE_REQUEST_LOG_DIR}"
mkdir -p "${SGLANG_PD_DECODE_REQUEST_METRICS_DIR}"
mkdir -p "${SGLANG_PD_DECODE_CRASH_DUMP_DIR}"

export MC_TCP_ENABLE_CONNECTION_POOL=1

echo "SGLang env setup done."
