#!/usr/bin/env bash

# Paths
export SGLANG_REPO_ROOT="${SGLANG_REPO_ROOT:-/workspace/sglang}"
export SGLANG_MS_DEV_DIR="${SGLANG_MS_DEV_DIR:-${SGLANG_REPO_ROOT}/ms_dev}"
export SGLANG_RUNTIME_DIR="${SGLANG_RUNTIME_DIR:-${SGLANG_MS_DEV_DIR}/runtime}"

# Python / venv
export PYTHON_BIN="${PYTHON_BIN:-/venv/main/bin/python3}"
export PIP_BIN="${PIP_BIN:-/venv/main/bin/pip}"

# Hugging Face cache
export HF_HOME="${HF_HOME:-/workspace/.hf_home}"
export HF_HUB_CACHE="${HF_HUB_CACHE:-${HF_HOME}/hub}"

# Server runtime files
export SGLANG_SERVER_LOG="${SGLANG_SERVER_LOG:-${SGLANG_RUNTIME_DIR}/server.log}"
export SGLANG_SERVER_PID_FILE="${SGLANG_SERVER_PID_FILE:-${SGLANG_RUNTIME_DIR}/server.pid}"
export SGLANG_REQUEST_LOG_DIR="${SGLANG_REQUEST_LOG_DIR:-${SGLANG_RUNTIME_DIR}/request_logs}"
export SGLANG_REQUEST_METRICS_DIR="${SGLANG_REQUEST_METRICS_DIR:-${SGLANG_RUNTIME_DIR}/request_metrics}"
export SGLANG_CRASH_DUMP_DIR="${SGLANG_CRASH_DUMP_DIR:-${SGLANG_RUNTIME_DIR}/crash_dump}"

# Model / server config
export SGLANG_MODEL_PATH="${SGLANG_MODEL_PATH:-meta-llama/Llama-3.1-8B-Instruct}"
export SGLANG_HOST="${SGLANG_HOST:-0.0.0.0}"
export SGLANG_PORT="${SGLANG_PORT:-30000}"
export SGLANG_ATTENTION_BACKEND="${SGLANG_ATTENTION_BACKEND:-triton}"
export SGLANG_SAMPLING_BACKEND="${SGLANG_SAMPLING_BACKEND:-pytorch}"
export SGLANG_MEM_FRACTION_STATIC="${SGLANG_MEM_FRACTION_STATIC:-0.85}"
export SGLANG_LOG_REQUESTS_LEVEL="${SGLANG_LOG_REQUESTS_LEVEL:-1}"
export SGLANG_LOG_REQUESTS_FORMAT="${SGLANG_LOG_REQUESTS_FORMAT:-json}"
export SGLANG_OTLP_TRACES_ENDPOINT="${SGLANG_OTLP_TRACES_ENDPOINT:-localhost:4317}"
export SGLANG_OTLP_EXPORTER_SCHEDULE_DELAY_MILLIS="${SGLANG_OTLP_EXPORTER_SCHEDULE_DELAY_MILLIS:-500}"
export SGLANG_OTLP_EXPORTER_MAX_EXPORT_BATCH_SIZE="${SGLANG_OTLP_EXPORTER_MAX_EXPORT_BATCH_SIZE:-64}"

# Extra args for sglang
export SGLANG_SERVE_EXTRA_ARGS="${SGLANG_SERVE_EXTRA_ARGS:-}"

mkdir -p "${SGLANG_RUNTIME_DIR}"
mkdir -p "${HF_HOME}"
mkdir -p "${HF_HUB_CACHE}"
mkdir -p "${SGLANG_REQUEST_LOG_DIR}"
mkdir -p "${SGLANG_REQUEST_METRICS_DIR}"
mkdir -p "${SGLANG_CRASH_DUMP_DIR}"
