#!/usr/bin/env bash

# PD disaggregation profile (prefill / decode / router).
# Sourced by sglang_start_server_pd_prefill.sh, sglang_start_server_pd_decode.sh,
# sglang_start_router_pd.sh (via env.sh).

if [[ -z "${SGLANG_REPO_ROOT:-}" ]]; then
  _ENV_PD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  source "${_ENV_PD_DIR}/env.common.sh"
fi

# Role-specific runtime dirs
export SGLANG_ROUTER_LOG_DIR="${SGLANG_ROUTER_LOG_DIR:-${SGLANG_RUNTIME_DIR}/router/logs}"

export SGLANG_PD_PREFILL_RUNTIME_DIR="${SGLANG_PD_PREFILL_RUNTIME_DIR:-${SGLANG_RUNTIME_DIR}/prefill}"
export SGLANG_PD_DECODE_RUNTIME_DIR="${SGLANG_PD_DECODE_RUNTIME_DIR:-${SGLANG_RUNTIME_DIR}/decode}"

export SGLANG_PD_PREFILL_REQUEST_LOG_DIR="${SGLANG_PD_PREFILL_REQUEST_LOG_DIR:-${SGLANG_PD_PREFILL_RUNTIME_DIR}/request_logs}"
export SGLANG_PD_PREFILL_REQUEST_METRICS_DIR="${SGLANG_PD_PREFILL_REQUEST_METRICS_DIR:-${SGLANG_PD_PREFILL_RUNTIME_DIR}/request_metrics}"
export SGLANG_PD_PREFILL_CRASH_DUMP_DIR="${SGLANG_PD_PREFILL_CRASH_DUMP_DIR:-${SGLANG_PD_PREFILL_RUNTIME_DIR}/crash_dump}"

export SGLANG_PD_DECODE_REQUEST_LOG_DIR="${SGLANG_PD_DECODE_REQUEST_LOG_DIR:-${SGLANG_PD_DECODE_RUNTIME_DIR}/request_logs}"
export SGLANG_PD_DECODE_REQUEST_METRICS_DIR="${SGLANG_PD_DECODE_REQUEST_METRICS_DIR:-${SGLANG_PD_DECODE_RUNTIME_DIR}/request_metrics}"
export SGLANG_PD_DECODE_CRASH_DUMP_DIR="${SGLANG_PD_DECODE_CRASH_DUMP_DIR:-${SGLANG_PD_DECODE_RUNTIME_DIR}/crash_dump}"

# Router metrics port
export SGLANG_ROUTER_PROMETHEUS_PORT="${SGLANG_ROUTER_PROMETHEUS_PORT:-39000}"

# PD ports (1 node / 2 GPUs default)
export SGLANG_PD_ROUTER_PORT="${SGLANG_PD_ROUTER_PORT:-31000}"
export SGLANG_PD_DECODE_PORT="${SGLANG_PD_DECODE_PORT:-31001}"
export SGLANG_PD_PREFILL_PORT="${SGLANG_PD_PREFILL_PORT:-31002}"

# PD base GPU IDs
export SGLANG_PD_PREFILL_BASE_GPU_ID="${SGLANG_PD_PREFILL_BASE_GPU_ID:-0}"
export SGLANG_PD_DECODE_BASE_GPU_ID="${SGLANG_PD_DECODE_BASE_GPU_ID:-1}"

# Router / backend host (host network => 127.0.0.1 is fine)
export SGLANG_PD_BACKEND_HOST="${SGLANG_PD_BACKEND_HOST:-127.0.0.1}"
export SGLANG_PD_ROUTER_HOST="${SGLANG_PD_ROUTER_HOST:-0.0.0.0}"

# Optional PD settings
export SGLANG_PD_IB_DEVICE="${SGLANG_PD_IB_DEVICE:-}"
export SGLANG_PD_PREFILL_EXTRA_ARGS="${SGLANG_PD_PREFILL_EXTRA_ARGS:-}"
export SGLANG_PD_DECODE_EXTRA_ARGS="${SGLANG_PD_DECODE_EXTRA_ARGS:-}"
export SGLANG_PD_ROUTER_EXTRA_ARGS="${SGLANG_PD_ROUTER_EXTRA_ARGS:-}"

# Prefill HiCache (safe to enable in PD mode).
export SGLANG_PD_PREFILL_HICACHE_ENABLE="${SGLANG_PD_PREFILL_HICACHE_ENABLE:-1}"
export SGLANG_PD_PREFILL_HICACHE_STORAGE_BACKEND="${SGLANG_PD_PREFILL_HICACHE_STORAGE_BACKEND:-file}"
export SGLANG_PD_PREFILL_HICACHE_PREFETCH_POLICY="${SGLANG_PD_PREFILL_HICACHE_PREFETCH_POLICY:-timeout}"
export SGLANG_PD_PREFILL_HICACHE_WRITE_POLICY="${SGLANG_PD_PREFILL_HICACHE_WRITE_POLICY:-write_back}"
export SGLANG_PD_PREFILL_HICACHE_IO_BACKEND="${SGLANG_PD_PREFILL_HICACHE_IO_BACKEND:-kernel}"
export SGLANG_PD_PREFILL_HICACHE_MEM_LAYOUT="${SGLANG_PD_PREFILL_HICACHE_MEM_LAYOUT:-page_first}"
export SGLANG_PD_PREFILL_HICACHE_RATIO="${SGLANG_PD_PREFILL_HICACHE_RATIO:-2}"
export SGLANG_PD_PREFILL_HICACHE_SIZE="${SGLANG_PD_PREFILL_HICACHE_SIZE:-256}" # in GB; 0 = auto
export SGLANG_PD_PREFILL_ENABLE_CACHE_REPORT="${SGLANG_PD_PREFILL_ENABLE_CACHE_REPORT:-1}"

# Decode offload / HiCache.
# Decode L2 HiCache currently conflicts with PD decode radix-cache in this SGLang
# version, so the default uses the disaggregation offload path (GPU KV -> host/storage)
# and keeps --enable-hierarchical-cache off. Overrides:
#   export SGLANG_PD_DECODE_OFFLOAD_ENABLE=0                   # disable decode offload
#   export SGLANG_PD_DECODE_HICACHE_STORAGE_BACKEND=mooncake   # or file/hf3fs
#   export MOONCAKE_MASTER=127.0.0.1:50051                     # when backend=mooncake
export SGLANG_PD_DECODE_OFFLOAD_ENABLE="${SGLANG_PD_DECODE_OFFLOAD_ENABLE:-1}"
export SGLANG_PD_DECODE_HICACHE_ENABLE="${SGLANG_PD_DECODE_HICACHE_ENABLE:-0}"
export SGLANG_PD_DECODE_HICACHE_STORAGE_BACKEND="${SGLANG_PD_DECODE_HICACHE_STORAGE_BACKEND:-file}"
export SGLANG_PD_DECODE_HICACHE_PREFETCH_POLICY="${SGLANG_PD_DECODE_HICACHE_PREFETCH_POLICY:-timeout}"
export SGLANG_PD_DECODE_HICACHE_WRITE_POLICY="${SGLANG_PD_DECODE_HICACHE_WRITE_POLICY:-write_back}"
export SGLANG_PD_DECODE_HICACHE_IO_BACKEND="${SGLANG_PD_DECODE_HICACHE_IO_BACKEND:-kernel}"
export SGLANG_PD_DECODE_HICACHE_MEM_LAYOUT="${SGLANG_PD_DECODE_HICACHE_MEM_LAYOUT:-page_first}"
export SGLANG_PD_DECODE_HICACHE_RATIO="${SGLANG_PD_DECODE_HICACHE_RATIO:-2}"
export SGLANG_PD_DECODE_HICACHE_SIZE="${SGLANG_PD_DECODE_HICACHE_SIZE:-256}" # in GB; 0 = auto
export SGLANG_PD_DECODE_ENABLE_CACHE_REPORT="${SGLANG_PD_DECODE_ENABLE_CACHE_REPORT:-1}"

# Disaggregation timeouts (seconds)
export SGLANG_DISAGGREGATION_BOOTSTRAP_TIMEOUT="${SGLANG_DISAGGREGATION_BOOTSTRAP_TIMEOUT:-900}"
export SGLANG_DISAGGREGATION_WAITING_TIMEOUT="${SGLANG_DISAGGREGATION_WAITING_TIMEOUT:-900}"

# PD router request timeout (seconds)
export SGLANG_PD_ROUTER_REQUEST_TIMEOUT_SECS="${SGLANG_PD_ROUTER_REQUEST_TIMEOUT_SECS:-900}"

mkdir -p "${SGLANG_ROUTER_LOG_DIR}"
mkdir -p "${SGLANG_PD_PREFILL_REQUEST_LOG_DIR}"
mkdir -p "${SGLANG_PD_PREFILL_REQUEST_METRICS_DIR}"
mkdir -p "${SGLANG_PD_PREFILL_CRASH_DUMP_DIR}"
mkdir -p "${SGLANG_PD_DECODE_REQUEST_LOG_DIR}"
mkdir -p "${SGLANG_PD_DECODE_REQUEST_METRICS_DIR}"
mkdir -p "${SGLANG_PD_DECODE_CRASH_DUMP_DIR}"
